import { IncomeEntity } from 'src/model/income/income.entity';
import { UserEntity } from 'src/model/user.entity';

export function getTestIncomesData(
  user: UserEntity,
): Omit<IncomeEntity, 'id'>[] {
  return [
    {
      amount: 873,
      comment: 'Income Transaction 1',
      date: new Date('2024-04-20'),
      type: 'salary',
      user,
    },
    {
      amount: 621,
      comment: 'Income Transaction 2',
      date: new Date('2024-04-06'),
      type: 'Interest Income',
      user,
    },
    {
      amount: 298,
      comment: 'Income Transaction 3',
      date: new Date('2024-04-29'),
      type: 'Other Income',
      user,
    },
    {
      amount: 564,
      comment: 'Income Transaction 4',
      date: new Date('2024-04-11'),
      type: 'salary',
      user,
    },
    {
      amount: 789,
      comment: 'Income Transaction 5',
      date: new Date('2024-04-23'),
      type: 'Investment Income',
      user,
    },
    {
      amount: 123,
      comment: 'Income Transaction 6',
      date: new Date('2024-04-08'),
      type: 'salary',
      user,
    },
    {
      amount: 456,
      comment: 'Income Transaction 7',
      date: new Date('2024-04-19'),
      type: 'Investment Income',
      user,
    },
    {
      amount: 987,
      comment: 'Income Transaction 8',
      date: new Date('2024-04-04'),
      type: 'Other Income',
      user,
    },
    {
      amount: 321,
      comment: 'Income Transaction 9',
      date: new Date('2024-04-14'),
      type: 'salary',
      user,
    },
    {
      amount: 654,
      comment: 'Income Transaction 10',
      date: new Date('2024-04-25'),
      type: 'Investment Income',
      user,
    },
    {
      amount: 234,
      comment: 'Income Transaction 11',
      date: new Date('2024-04-17'),
      type: 'salary',
      user,
    },
    {
      amount: 123,
      comment: 'Income Transaction 12',
      date: new Date('2024-04-28'),
      type: 'Investment Income',
      user,
    },
    {
      amount: 345,
      comment: 'Income Transaction 13',
      date: new Date('2024-04-03'),
      type: 'Other Income',
      user,
    },
    {
      amount: 765,
      comment: 'Income Transaction 14',
      date: new Date('2024-04-10'),
      type: 'salary',
      user,
    },
    {
      amount: 923,
      comment: 'Income Transaction 15',
      date: new Date('2024-04-22'),
      type: 'Investment Income',
      user,
    },
    {
      amount: 876,
      comment: 'Income Transaction 16',
      date: new Date('2024-04-09'),
      type: 'salary',
      user,
    },
    {
      amount: 873,
      comment: 'Income Transaction 1',
      date: new Date('2024-04-20'),
      type: 'salary',
      user,
    },
    {
      amount: 621,
      comment: 'Income Transaction 2',
      date: new Date('2024-04-06'),
      type: 'Interest Income',
      user,
    },
    {
      amount: 298,
      comment: 'Income Transaction 3',
      date: new Date('2024-04-29'),
      type: 'Other Income',
      user,
    },
    {
      amount: 564,
      comment: 'Income Transaction 4',
      date: new Date('2024-04-11'),
      type: 'salary',
      user,
    },
    {
      amount: 789,
      comment: 'Income Transaction 5',
      date: new Date('2024-04-23'),
      type: 'Investment Income',
      user,
    },
    {
      amount: 123,
      comment: 'Income Transaction 6',
      date: new Date('2024-04-08'),
      type: 'salary',
      user,
    },
    {
      amount: 456,
      comment: 'Income Transaction 7',
      date: new Date('2024-04-19'),
      type: 'Investment Income',
      user,
    },
    {
      amount: 987,
      comment: 'Income Transaction 8',
      date: new Date('2024-04-04'),
      type: 'Other Income',
      user,
    },
    {
      amount: 321,
      comment: 'Income Transaction 9',
      date: new Date('2024-04-14'),
      type: 'salary',
      user,
    },
    {
      amount: 654,
      comment: 'Income Transaction 10',
      date: new Date('2024-04-25'),
      type: 'Investment Income',
      user,
    },
    {
      amount: 234,
      comment: 'Income Transaction 11',
      date: new Date('2024-04-17'),
      type: 'salary',
      user,
    },
    {
      amount: 123,
      comment: 'Income Transaction 12',
      date: new Date('2024-04-28'),
      type: 'Investment Income',
      user,
    },
    {
      amount: 345,
      comment: 'Income Transaction 13',
      date: new Date('2024-04-03'),
      type: 'Other Income',
      user,
    },
    {
      amount: 765,
      comment: 'Income Transaction 14',
      date: new Date('2024-04-10'),
      type: 'salary',
      user,
    },
    {
      amount: 923,
      comment: 'Income Transaction 15',
      date: new Date('2024-04-22'),
      type: 'Investment Income',
      user,
    },
  ];
}
